//
// Created by shecannotsee on 2023/3/17.
//

#ifndef DATA_STRUCTURE_CORE_SRC_TREE_BINARY_SEARCH_TREE_H_
#define DATA_STRUCTURE_CORE_SRC_TREE_BINARY_SEARCH_TREE_H_

class binary_search_tree {

};

#endif //DATA_STRUCTURE_CORE_SRC_TREE_BINARY_SEARCH_TREE_H_
