//
// Created by shecannotsee on 2023/3/17.
//

#ifndef DATA_STRUCTURE_CORE_SRC_LINEAR_SINGLE_LINKED_LIST_H_
#define DATA_STRUCTURE_CORE_SRC_LINEAR_SINGLE_LINKED_LIST_H_

class single_linked_list {

};

#endif //DATA_STRUCTURE_CORE_SRC_LINEAR_SINGLE_LINKED_LIST_H_
